"""Fetch authoritative BibTeX entries from the arXiv API for all project references.

Stdlib-only on purpose (runs even before the uv env exists):
    python3 shared/fetch_bib.py

Writes refs.bib to REPLAY/latex/ and WildLoop/latex/ (same bibliography for both).
Add new papers to ARXIV_IDS below, rerun, commit. Never hand-edit refs.bib -
it is generated; hand edits go to extra_refs.bib next to it (kept if present).
"""
from __future__ import annotations

import re
import time
import urllib.request
import xml.etree.ElementTree as ET
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
TARGETS = [
    PROJECT_ROOT / "REPLAY" / "latex" / "refs.bib",
    PROJECT_ROOT / "WildLoop" / "latex" / "refs.bib",
]

# cite_key -> arXiv id
ARXIV_IDS = {
    # --- anchors ---
    "skillopt2026": "2605.23904",
    "skillrm2026": "2606.03980",
    "tfgrpo2025": "2510.08191",
    "skillscoach2026": "2604.27488",
    # --- text-space optimizers / experience libraries ---
    "reflexion2023": "2303.11366",
    "voyager2023": "2305.16291",
    "expel2023": "2308.10144",
    "promptbreeder2023": "2309.16797",
    "opro2023": "2309.03409",
    "autoguide2024": "2403.08978",
    "mipro2024": "2406.11695",
    "textgrad2024": "2406.07496",
    "trace2024": "2406.16218",
    "awm2024": "2409.07429",
    "skillweaver2025": "2504.07079",
    "gepa2025": "2507.19457",
    "memento2025": "2508.16153",
    "ace2025": "2510.04618",
    "reasoningbank2025": "2509.25140",
    "edv2026": "2606.24428",
    "selfevolvingsurvey2025": "2507.21046",
    "agenticskillssok2026": "2602.20867",
    "skillsvote2026": "2605.18401",
    # --- interaction logs / implicit feedback / judges ---
    "wildchat2024": "2405.01470",
    "natfeedback2024": "2407.10944",
    "noisyfeedback2025": "2507.23158",
    "respect2024": "2410.13852",
    "rluf2025": "2505.14946",
    "implicitsentiment2025": "2509.18361",
    "kto2024": "2402.01306",
    "rlthf2025": "2502.13417",
    "taubench2024": "2406.12045",
    "tau2bench2025": "2506.07982",
    "lostinsim2026": "2601.17087",
    "realusersim2026": "2605.20204",
    "judgereliability2026": "2606.19544",
    "wiseflow2026": "2601.08158",
    "grasp2026": "2605.29668",
    "judgeauroc2026": "2606.09863",
    "prodjudge2026": "2606.10315",
    "appworld2024": "2407.18901",
    "rewardhackbench2026": "2605.02964",
    "impossiblebench2025": "2510.20270",
    "evilgenie2025": "2511.21654",
    "rewardhackingrubric2026": "2606.04923",
    "manipulation2024": "2411.02306",
    "nubank2026": "2606.08867",
}

ATOM = "{http://www.w3.org/2005/Atom}"


def fetch(ids: list[str]) -> dict[str, dict]:
    url = "http://export.arxiv.org/api/query?id_list=" + ",".join(ids) + f"&max_results={len(ids)}"
    with urllib.request.urlopen(url, timeout=60) as r:
        root = ET.fromstring(r.read())
    out = {}
    for entry in root.iter(f"{ATOM}entry"):
        raw_id = entry.findtext(f"{ATOM}id", "")
        m = re.search(r"abs/([0-9.]+)", raw_id)
        if not m:
            continue
        out[m.group(1)] = {
            "title": re.sub(r"\s+", " ", entry.findtext(f"{ATOM}title", "").strip()),
            "authors": [a.findtext(f"{ATOM}name", "") for a in entry.iter(f"{ATOM}author")],
            "year": entry.findtext(f"{ATOM}published", "")[:4],
        }
    return out


def to_bibtex(key: str, arxiv_id: str, meta: dict) -> str:
    authors = " and ".join(meta["authors"]) or "{arXiv:" + arxiv_id + "}"
    return (
        f"@misc{{{key},\n"
        f"  title  = {{{meta['title']}}},\n"
        f"  author = {{{authors}}},\n"
        f"  year   = {{{meta['year']}}},\n"
        f"  eprint = {{{arxiv_id}}},\n"
        f"  archivePrefix = {{arXiv}},\n"
        f"  url    = {{https://arxiv.org/abs/{arxiv_id}}},\n"
        f"}}\n"
    )


def main() -> None:
    ids = list(ARXIV_IDS.values())
    meta: dict[str, dict] = {}
    for i in range(0, len(ids), 20):  # arXiv API is politer in small batches
        meta.update(fetch(ids[i : i + 20]))
        time.sleep(1)
    blocks, missing = [], []
    for key, aid in sorted(ARXIV_IDS.items()):
        if aid in meta and meta[aid]["title"]:
            blocks.append(to_bibtex(key, aid, meta[aid]))
        else:
            missing.append(f"% MISSING from arXiv API: {key} = {aid}\n")
    header = "% AUTO-GENERATED by shared/fetch_bib.py - do not hand-edit (see file docstring)\n\n"
    content = header + "".join(blocks) + "".join(missing)
    for target in TARGETS:
        extra = target.parent / "extra_refs.bib"
        target.write_text(content + (extra.read_text() if extra.exists() else ""))
        print(f"wrote {target}  ({len(blocks)} entries, {len(missing)} missing)")


if __name__ == "__main__":
    main()
